modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="quietlogs"
version="${version}"
displayName="Quiet Logs"
description="Suppresses various mod log spam to keep your logs clean"
authors="tinywifi"

[[dependencies.quietlogs]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.quietlogs]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"